name: Update World Clock Data

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz  # Add any other dependencies your script requires

    - name: Run the World Clock update script
      run: python update_world_clock.py
